site_name: "Pendulum Whitepaper"
site_description: "Whitepaper for Pendulum"
site_author: "team@pendulum.tech"

pages:
  - Home: index.md
  - Introduction: introduction.md
  - Pendulum Protocols Overview: protocol.md
  - Smart Pricing: pricing.md
  - Trust Graph and Reputation: reputation.md
  - Relevance Mechanism: relevance.md
  - Staking Mechanism: staking.md
  - Use Cases: use-cases.md
  - Roadmap: roadmap.md
  - Meet the Team: team.md
  - About:
    - Reviewers: about/reviewers.md
    - License: about/license.md

theme:
  name: "material"
  language: "en"
  palette:
    primary: "deep purple"
    accent: "deep purple"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo:
    icon: "layers"
    
docs_dir: "pages"
site_dir: "docs"
extra_css: [styles/styles.css]